mercure:
    hubs:
        default:
            url: '%env(MERCURE_URL)%'
            public_url: '%env(MERCURE_PUBLIC_URL)%'
            jwt:
                algorithm: 'hmac.sha256'
                provider: App\Service\Mercure\JWTProvider
