<?php

namespace ContainerAMBnicH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJWTProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Service\Mercure\JWTProvider' shared autowired service.
     *
     * @return \App\Service\Mercure\JWTProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mercure/src/Jwt/TokenProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Service/Mercure/JWTProvider.php';

        return $container->services['App\\Service\\Mercure\\JWTProvider'] = new \App\Service\Mercure\JWTProvider(($container->services['.container.private.session'] ?? $container->load('get_Container_Private_SessionService')), ($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container))));
    }
}
