<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAMBnicH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAMBnicH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAMBnicH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAMBnicH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAMBnicH\App_KernelDevDebugContainer([
    'container.build_hash' => 'AMBnicH',
    'container.build_id' => 'f953a227',
    'container.build_time' => 1663491818,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAMBnicH');
