<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'publish' => [[], ['_controller' => 'App\\Controller\\MercureController::publish'], [], [['text', '/publish']], [], [], []],
    'generate' => [[], ['_controller' => 'App\\Controller\\MercureController::generateJwt'], [], [['text', '/generate']], [], [], []],
];
